name: Test deployment

on:
  push:
    branches: ["*"]
  # note: not testing on PR, since we are already previews for PRs
  # which have the same effect
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  #   branches:
  #     - "main**"

jobs:
  test-deploy:
    name: Test deployment
    if: (github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    steps:
      # NOTE: for debugging CI this allow shell access to github runner. Will print out tmate.io terminal url
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true
      #   timeout-minutes: 15
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test build website
        run: bun run build
