name: Test deployment

on:
  pull_request:
    branches: ["*"]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: bun install
      - name: Test build website
        run: bun run build
